#!/usr/bin/env python3
"""Generate the Deferred Work Register from a review table.
Guarantees every DWR-001 required field is present on every entry."""
import yaml, sys

REQ = ["dwr_id","title","category","class","origin","discussion_reference","date_identified",
       "reason_deferred","executive_context","dependencies","trigger_event","estimated_value",
       "estimated_complexity","recommended_priority","current_status"]

D = "DECISION"; I = "IMPLEMENTATION"
# id, title, cat, class, origin, ref, date, reason, exec_ctx, deps, trigger, value, cx, prio, status
ROWS = [
# ---------------- DEFERRED DECISIONS ----------------
("DWR-001","Define MANDATORY_SILENCE scope: no score vs no sound","D — Governance Debt",D,
 "Sprint 3A / RE-001 finding SLF-01","PDR-2026-08-22-ESS-004; CONDUCTOR_SCORE.yaml silence_law_integrity_findings","2026-08-22",
 "Content of the audio element inside SIL-01 was never inspected; source media offline (delta D-22). Classified UNCERTAIN and escalated rather than judged.",
 "Executive Team named this the highest-consequence of the four PDRs: it defines a platform rule, not only a production fact.",
 "62-second human listen to 00:33:37.708-00:34:39.667 of the locked cut","Audio inspection completed and content classified",
 "HIGH — resolves years of ambiguity in one ruling","LOW (one listen + one ruling)","P1","Deferred"),
("DWR-002","S16 segment label vs observed illumination","D — Production","DECISION",
 "Sprint 3A conflict VCONF-01","PDR-2026-08-22-ESS-001","2026-08-22",
 "Registries outrank visual observation; DIE-V recorded CONFLICTED and stopped.",
 "Reaches CUE-08 (Pass 4 CELEBRATION). Boundary is correct to 0.5s; only the label disagrees.",
 "None","Executive disposition of the four Sprint 3A PDRs",
 "MEDIUM","LOW","P2","Deferred"),
("DWR-003","Escort ride duration vs CUE-03 span","D — Production",D,
 "Sprint 3A conflict VCONF-02","PDR-2026-08-22-ESS-002","2026-08-22",
 "Cue sheet is ARCHITECTURE APPROVED; extending a cue is musical intent, not measurement.",
 "~150s of escort ride carries no cue; SIL-01 opens over moving ride footage.",
 "DWR-001 (same silence zone)","Executive disposition; should be taken with DWR-001",
 "MEDIUM-HIGH","LOW-MEDIUM","P1","Deferred"),
("DWR-004","Caption policy vs zero rider lower-thirds (consent dimension)","D — Production",D,
 "Sprint 3A conflict VCONF-03","PDR-2026-08-22-ESS-003","2026-08-22",
 "Absence of an artifact is not proof the intent was abandoned; deciding is editorial.",
 "Carries a consent and rights dimension: RIDER_REGISTRY names are largely UNCONFIRMED under R-3.",
 "RIDER_REGISTRY resolution status; consent ledger","Executive disposition",
 "MEDIUM","LOW (option A) to HIGH (option C reopens picture lock)","P3","Deferred"),
("DWR-005","Reconcile the two PDR numbering schemes","D — Governance Debt",D,
 "PDR-2026-08-20-ETC-001 header, self-flagged","PDR-2026-08-20-ETC-001 'Numbering: date-typed scheme, as-issued (reconcile w/ pilot sequence in docs/README)'","2026-08-20",
 "Recorded as-issued to avoid blocking the ETC ruling; reconciliation explicitly postponed to docs/README.",
 "Two live schemes and two storage trees: docs/pdr/PDR-YYYY-MM-DD-TYPE-NNN (markdown) and records/pdr/PDR-00000N (YAML). Never reconciled.",
 "docs/README numbering policy","Next PDR issued, or PHI-001 disposition",
 "HIGH — ambiguity in the platform's most-used record class","LOW (a ruling + a migration note)","P1","Deferred"),
("DWR-006","Separate 'Workman Experience Technologies LLC' formation","D — Business/Entity",D,
 "WET-WF-001 Gap Register GAP-01 (AMENDED, Ruling 3)","docs/reports/WET-WF-001_Gap_Register_Addendum_v1.1.md GAP-01","2026-08-11",
 "DBA-instead decision: DBA filed under Workman Experience, LLC (TX 804929409, 2026-07-21).",
 "Explicitly recorded as deliberately deferred. Resume claims referencing only the DBA are accurate; claims implying a standalone WET LLC remain inaccurate until formed.",
 "None","Business need for a standalone entity",
 "LOW (platform) / MEDIUM (positioning)","MEDIUM (legal, external)","P4","Deferred"),
("DWR-007","Cue-boundary reconciliation as a pre-generation gate","D — Architecture",D,
 "Sprint 3A engineering reflection; carried as AI-02","DOC-SRC-001 section 1 bullet 9; G3-ESS-001_EXECUTIVE_CONFIRMATION AI-02","2026-08-22",
 "Raised at run completion; no authority to change the MIE pipeline during Sprint 3A.",
 "Would prevent writing beds against spans that end 2.5 minutes before the action does (VCONF-02 class of error).",
 "DWR-003 outcome","Next MIE pass planning",
 "HIGH — prevents a whole error class","LOW-MEDIUM","P2","Deferred"),
("DWR-008","Chairman countersignature on platform-scope artifacts","D — Governance Debt",D,
 "PHI-001 predecessor work; carried as AI-06","G3-ESS-001_EXECUTIVE_CONFIRMATION section 4.7","2026-08-22",
 "Ratified on Executive Producer authority; every prior platform-scope artifact carries Chairman acceptance.",
 "Affects WET-SPEC-GATE-001, DOC-001, DOC-002. Flagged rather than assumed.",
 "None","Chairman review session",
 "MEDIUM — authority consistency","LOW","P2","Deferred"),
("DWR-009","Ratify remaining doctrine candidates DC-02 through DC-10","D — Governance",D,
 "DOC-SRC-001 section 2; carried as AI-03","docs/doctrine/DOC-SRC-001 section 3 AI-03","2026-08-22",
 "Ratification is a separate act from preservation; only DC-01 was promoted.",
 "Nine candidates remain explicitly NON-NORMATIVE.",
 "None","Chairman review session",
 "MEDIUM","LOW","P3","Deferred"),
("DWR-010","Confirm whether 'Production Intelligence Score' is already decided","D — Governance Debt",D,
 "PHI-001 special review request vs WET-WF-001 GAP-03","GAP-03 locked design decision: 'No single 0-100 health score; component metrics + plain-English verdict only'","2026-08-11",
 "A locked design decision already rejects a single composite score for the Production Health Report. Whether that ruling extends to a 'Production Intelligence Score' has never been stated.",
 "The Executive Team listed Production Intelligence Score as a topic of interest; the governed record may already answer it.",
 "None","PHI-001 disposition",
 "HIGH — prevents re-litigating a settled decision","VERY LOW (one clarifying ruling)","P1","Completed"),
("DWR-011","CURATED as a ratification candidate in the provenance vocabulary","D — Governance",D,
 "Part 1 governance pilot vocabulary rulings","docs/reports/PMR-001_Pilot_Metrics_Report.md 'CURATED admitted as ratification candidate (human-authorship/copyright rationale)'","2026-08-08",
 "Admitted as a candidate, never ratified. APPROVED was rejected as a provenance class twice.",
 "Touches ADR-003 harmonization and the OBSERVED/DERIVED/INTERPOLATED/ENRICHED/GENERATED vocabulary.",
 "ADR-003 (referenced, absent from this repository)","Provenance vocabulary revision",
 "MEDIUM","LOW","P3","Deferred"),
("DWR-012","WET-SPEC-002 v0.3 consolidations: rights-ledger primacy and timeline.format","D — Governance Debt",D,
 "WET-REV-002 required consolidations","docs/reviews/WET-REV-002_PDR_Disposition.md items 2 and 4; PMR-001 '2 outstanding for v0.3'","2026-08-07",
 "Two of four consolidations landed in v0.2; two were carried to v0.3.",
 "records/specs/WETSPEC002_v0.3 exists in the other governance tree - conformance to the two outstanding items is unverified by this review.",
 "PDR numbering reconciliation (DWR-005)","v0.3 ratification",
 "MEDIUM-HIGH","LOW-MEDIUM","P2","Under Review"),
("DWR-013","Independence disclosure for WET-SPEC-002 v0.3","D — Governance Debt",D,
 "WET-GAP-001 finding adopted under Ruling 2","WET-WF-001 Gap Register: 'v0.2 author = v0.1 reviewer -> v0.3 needs a different reviewer'","2026-08-11",
 "Single-operator condition; CAR-001 A4 later formalised independence disclosure.",
 "PDR-000003 already records the single-operator condition explicitly (section 7 Rule 6).",
 "CAR-001 Rev A independence disclosure form","v0.3 review",
 "MEDIUM","LOW","P3","Deferred"),
# ---------------- DEFERRED IMPLEMENTATIONS ----------------
("DWR-014","DJI / Insta360 telemetry parser (Pillar 2)","G — Future Capability",I,
 "we_capture Phase 1 planning","we_capture/PHASE1_PLANNING.md Pillar 2 (DEFERRED - evidence-driven)","2026-07 (approx)",
 "Evidence-driven deferral: on 103 real files the 9 timestamp fallbacks were .crdownload partials and a PDF, not DJI files. DJI_YYYYMMDDHHMMSS names already parse at fallback_level=0.",
 "Explicit trigger recorded in the source document. PI-04 compliance remains open; GPS redaction not required until GPS is actually extracted.",
 "None","A production run shows DJI files at fallback_level=2",
 "LOW until triggered","MEDIUM","P4","Deferred"),
("DWR-015","Camera Identity Robustness - full multi-layer system","C — Architectural Debt",I,
 "WET-WF-001 Gap Register GAP-04","GAP-04 'Elevated to foundational priority in engineering channel; not a polish item'","2026-08-11",
 "Content-based correction of mislabeled cards is proven in production; the full layered system was not built.",
 "Target: metadata/serial -> cameras.yaml mapping -> structure-based brand -> label as weakest hint -> conflict stop -> confirmation prompts. THIS IS THE SUBSTANCE OF THE 'CAPTURE DEVICE REGISTRY' TOPIC.",
 "cameras.yaml governance (DWR-016)","Next capture-side development cycle",
 "HIGH — novice-safety and identity correctness","MEDIUM-HIGH","P2","Deferred"),
("DWR-016","Bring cameras.yaml under governance as a named registry","B — Naming Hygiene",I,
 "PHI-001 review finding","cameras.yaml at repository root; self-described 'Camera Identity Registry ... SOURCE OF TRUTH'","2026-08-22",
 "Grew organically as a config file alongside the capture engine; never enrolled as a governed registry.",
 "It is the substance of the 'Capture Device Registry' the Executive Team remembers. It carries no registry_id, no registry_version, no schema version, and sits at repository root outside every governance tree.",
 "DIE spec registry framework F-1..F-5","PHI-001 disposition",
 "HIGH — closes a memory-only topic with an artifact that already exists","LOW","P1","Deferred"),
("DWR-017","SRT telemetry unit tests before promotion to VALIDATED","E — Technical Debt",I,
 "WET-WF-001 Gap Register GAP-02","GAP-02 'Unit tests for present / absent / malformed / gate-off required before promotion to VALIDATED'","2026-08-11",
 "Integration complete and config-gated (default false); promotion criteria stated but not met.",
 "Status is BUILT, not VALIDATED. GPS deliberately excluded from the pipeline path (privacy separation via telemetry.db).",
 "None","Before enabling timestamp.enable_srt_telemetry in production",
 "MEDIUM","LOW","P2","Deferred"),
("DWR-018","Production Health Report - full feature","F — Platform Opportunity",I,
 "WET-WF-001 Gap Register GAP-03","GAP-03 status: EXERCISED (basic clock audit) / DESIGN-COMPLETE (full feature); SPEC_Production_Health_Report.md","2026-08-11",
 "Design locked; only the basic clock audit was exercised in production.",
 "Design decisions already locked, including the rejection of a single 0-100 score. This is the nearest governed relative of the 'Production Intelligence Dashboard' topic.",
 "DWR-010 (score decision clarity)","Next production cycle",
 "HIGH","MEDIUM","P2","Deferred"),
("DWR-019","Full external-drive encryption execution","E — Technical Debt",I,
 "WET-WF-001 Gap Register GAP-06","GAP-06 status: ADOPTED (decisions) / OPEN (full external-drive encryption execution); SECURITY_RISK_ANALYSIS.md","2026-08-11",
 "Decisions D1-D4 adopted; execution across drives that leave the building not completed.",
 "FileVault on internal is in place. The gap is selective encryption for travelling drives.",
 "None","Before media leaves the building at scale",
 "HIGH (risk reduction)","MEDIUM","P2","Deferred"),
("DWR-020","STAGING_P2 closure path - grouping intelligence into edit usage","C — Architectural Debt",I,
 "WET-WF-001 Gap Register GAP-05","GAP-05 'Grouping engine is ready; edit usage of that intelligence was bypassed. Closure remains via STAGING_P2 path.'","2026-08-11",
 "Suite-validated engine; never production-used for the Part 1 edit.",
 "A built capability that has never delivered production value - the highest-leverage kind of deferred work.",
 "None","Part 3 edit planning",
 "HIGH — value already built, not yet realised","LOW-MEDIUM","P1","Deferred"),
("DWR-021","Packaged, signed dashboard application (.dmg path)","F — Platform Opportunity",I,
 "Dashboard prototype under custody","scripts/README_dashboard.md 'prototype / reference implementation ... not the packaged, signed app - that is the future .dmg path'","2026-06-30",
 "Prototype proves the 100% local, zero-CDN, zero-network mandate is achievable; packaging deferred.",
 "A working local read-only dashboard ALREADY EXISTS over the capture registry. This is the nearest governed relative of the 'Executive Dashboard' topic.",
 "Code signing / notarization (DWR-030)","Operational deployment need",
 "MEDIUM-HIGH","MEDIUM-HIGH","P3","Deferred"),
("DWR-022","CAR_ROADMAP.md - the CAR pipeline document","D — Governance Debt",I,
 "CAR-001 Rev A engineering amendment A1","CAR-001 A1 'CAR numbers identify review EVENTS ... never pre-allocated (pipeline: CAR_ROADMAP.md)'","2026-08-21",
 "The amendment was ratified referencing a pipeline document that was never created.",
 "A ratified governance instrument points at a file that does not exist. The eight planned reviews currently live in a single table cell in CAR_INDEX.md.",
 "None","PHI-001 disposition",
 "HIGH — a ratified reference must resolve","VERY LOW","P1","Deferred"),
("DWR-023","INTERVIEW_REGISTRY - spec-required, absent from disk","D — Governance Debt",I,
 "WET-SPEC-DIE-001 v0.2 section 7","Spec names nine registries; INTERVIEW_REGISTRY exists only in the specification text","2026-08-20",
 "Not created during Sprint 2 registry population; no empty-registry report was filed either.",
 "DIE spec V-5 requires populating all nine registries OR reporting each empty registry with a reason. Neither was done. The Sprint 3A communique named 'Interview Registry' as an ESS fusion input.",
 "DIE spec V-5","PHI-001 disposition",
 "HIGH — a frozen spec requirement is silently unmet","LOW (create, or file the empty-registry report)","P1","Deferred"),
("DWR-024","Cue custody rows in the registry","E — Technical Debt",I,
 "WET-GAP-001 finding adopted under Ruling 2","WET-WF-001 Gap Register: 'Registry = 726 camera rows, ZERO cue rows. Ungoverned-intelligence-layer risk is proven.'","2026-08-11",
 "The registry models the capture domain; the intelligence/cue domain was never given custody rows.",
 "Two BLACKTOP versions exist on disk without custody of which was accepted. The risk is described in the record as proven, not theoretical.",
 "PRS-001 (deferred)","Next intelligence-layer development cycle",
 "HIGH","MEDIUM","P2","Deferred"),
("DWR-025","ER-2 full session export, ER-4 manifest rights line, ER-5 license basis","D — Governance Debt",I,
 "WET-GAP-001 / Ruling 2 evidence requests","WET-WF-001 Gap Register ER list; PDR-000003 shows restrictions 'PENDING (ER-5)' and empty gate_clearance_ref","2026-08-11",
 "ER-1 (fresh FCPXML) was the convergent next action and is now satisfied for Part 2; ER-2/4/5 were not tracked to closure.",
 "ER-4 had a ready-to-run fix script in the Gap Register. Current status of all three is unverified by this review.",
 "None","Before GATE 2/3 on any release",
 "HIGH (publication-blocking)","LOW","P1","Under Review"),
("DWR-026","Rights-line coverage for KICKSTANDS UP v1 and other placed cues","D — Governance Debt",I,
 "PHI-001 predecessor finding; carried as AI-05","PDR-000003 coverage note: 'at least four additional placed cues (SLAB TALK, KICKSTANDS UP v1, Yo KICKSTANDS UP, The Piney Woods Transition) with no PDRs and no manifest rights lines'; 'record coverage is 2 of >=6 cue decisions'","2026-08-22",
 "Raised during the Sprint 3A confirmation but not created as a fifth PDR - the Executive Team had accepted a set of four.",
 "KICKSTANDS UP v1 is the single score asset in the Part 2 lock (00:00:00.000-00:01:16.417). GATE 2/3 require rights lines for ALL placed cues. Does not block MIE; blocks publication.",
 "DWR-025","Before GATE 2 on Part 2",
 "VERY HIGH — publication-blocking and currently unowned","LOW-MEDIUM","P1","Deferred"),
("DWR-027","Eight planned Collaborative Architecture Reviews","G — Future Capability",I,
 "CAR_INDEX row 3","CAR_INDEX.md: Production Intelligence Review · Digital Provenance & Asset Lineage · PBOM · Executive Dashboard & Analytics · Road Soul Lexicon · Conductor's Score Evolution · Platform Metrics · AI Governance Evolution","2026-08-21",
 "Listed as Planned (unnumbered per A1) - CAR numbers are assigned when a review convenes.",
 "This single table cell is the platform's entire forward review pipeline and holds five of the topics the Executive Team asked this review to find, including DPAL spelled out in full.",
 "DWR-022 (CAR_ROADMAP.md)","Each review convening",
 "VERY HIGH — this cell IS the institutional memory of the roadmap","LOW to expand into a roadmap document","P1","Deferred"),
("DWR-028","Retroactive Part 1 PDRs (8-10 records)","D — Governance Debt",I,
 "WET-REV-002 exercise-first order","WET-REV-002: 'Populate 8-10 retroactive PDRs from Part 1 decisions ... BEFORE v0.2 refinement'","2026-08-07",
 "Two pilots were authored (PDR-000003, PDR-000004); the remaining 6+ were not.",
 "PMR-001 records 'PDRs piloted: 2; pending: 6+'. The exercise-first order also gated PRS-001 and WET-SPEC-003.",
 "DWR-005 (numbering)","v0.3 refinement, or Part 1 archival",
 "MEDIUM-HIGH","MEDIUM","P2","Deferred"),
("DWR-029","Complete the two PDR pilots (BLACKTOP HYPNOSIS, OUT HERE)","D — Governance Debt",I,
 "WET-GAP-001 finding","Both recorded EXERCISED-INCOMPLETE (Draft); validator fails timeline.in/out because the Jul 29 FCPXML predates both cue decisions","2026-08-11",
 "Blocked on evidence (fresh FCPXML), which ER-1 has since produced for Part 2 but not for Part 1.",
 "PDR-000003 status is 'Draft', advancement gated on ER-2, ER-4, ER-5.",
 "DWR-025","Part 1 FCPXML re-export",
 "MEDIUM","LOW-MEDIUM","P3","Deferred"),
("DWR-030","Automated CI/CD, code signing/notarization, external security audit","E — Technical Debt",I,
 "MILESTONES.md honest verdict","MILESTONES.md: 'no automated CI/CD (tests are run on demand), no code signing/notarization, no external security audit'","2026-07-07",
 "Solo-developed, single-machine operating envelope; explicitly named as the gap between engineered-like-production and shipped-audited-deployed.",
 "The document is unusually candid about this and treats it as a known envelope, not an oversight.",
 "None","Contract deployment or external distribution",
 "HIGH for external deployment; LOW while single-operator","HIGH","P3","Deferred"),
("DWR-031","Machine-readable GATE 1/2/3","D — Governance Debt",I,
 "Gate Ledger Standard conformance table; carried as AI-04","WET-SPEC-GATE-001 section 9: publication gates are 'prose-only in SOP-06 - not yet machine-readable'","2026-08-22",
 "Re-expressing ratified gate law (CAPE clauses 17-19) is a Chairman act, not an implementation convenience.",
 "The gates with real consequences are the ones a dashboard currently cannot read.",
 "DWR-008 (Chairman session)","Chairman review session",
 "HIGH — observability of release authority","LOW-MEDIUM","P2","Deferred"),
("DWR-032","Full-resolution unwatermarked proxy for DIE-V","F — Platform Opportunity",I,
 "Sprint 3A delta D-24; carried as AI-01","RE-001 section 7; DOC-SRC-001 section 1 bullet 8","2026-08-22",
 "Sprint 3A was supplied a 320x180 watermarked proxy as visual ground truth.",
 "Caps every visual observation. Formation geometry, flag identification and camera-motion separation are unavailable at this resolution - a better proxy, not a better method.",
 "None","Before Sprint 4 DIE-V work",
 "HIGH","LOW (supply an export)","P1","Deferred"),
("DWR-033","RE-002 - regeneration after PDR disposition","F — Platform Opportunity",I,
 "Gate on_open.required_actions","intelligence/p2/ess/DOWNSTREAM_AUTHORIZATION_GATE.yaml on_open","2026-08-22",
 "Cannot occur until the four Sprint 3A PDRs are dispositioned.",
 "Closes Level 7 (Continuous Improvement): a scorecard index with one row is a baseline, not a trend.",
 "DWR-001..DWR-004","All four Sprint 3A PDRs dispositioned",
 "HIGH — makes platform evolution measurable","LOW (mechanism already armed)","P1","Deferred"),
("DWR-034","PRS-001 storage internals specification","G — Future Capability",I,
 "WET-REV-002 deferral","WET-REV-002: 'PRS-001 and WET-SPEC-003 remain deferred until then' (after retroactive PDRs)","2026-08-07",
 "Deferred behind the exercise-first order.",
 "PMR-001 owes 'exact registry count: TBD (A2/PRS-001)' to this specification.",
 "DWR-028","Retroactive PDR exercise complete",
 "MEDIUM","MEDIUM-HIGH","P4","Deferred"),
("DWR-035","WET-SPEC-003 (platform-core, number reserved)","G — Future Capability",I,
 "WET-REV-002 deferral","WET-REV-002; docs/README sequential platform-core series","2026-08-07",
 "Deferred behind the exercise-first order; the number remains unallocated.",
 "Relevant to numbering hygiene: WET-SPEC-GATE-001 deliberately used the named series to avoid taking this reserved number.",
 "DWR-028","Exercise-first order satisfied",
 "LOW until scoped","UNKNOWN","P4","Deferred"),
("DWR-036","Transmit 5 local commits to origin/main","E — Technical Debt",I,
 "Sprint 3A / PHI-001 execution environment; carried as AI-07","G3-ESS-001_EXECUTIVE_CONFIRMATION AI-07","2026-08-22",
 "The execution sandbox has no network egress and no SSH credentials; push fails host key verification.",
 "Environmental, not architectural. The commits exist and are complete; they need transmitting.",
 "Operator with repository credentials","Next operator session at the machine",
 "HIGH — unpushed governance is unshared governance","VERY LOW (one command)","P1","Deferred"),
]

RESOLUTIONS = {
 "DWR-010": {
   "resolution": ("EXTEND GAP-03. Executive Ruling, 2026-08-22. The prohibition on composite "
                  "readiness/health scores is extended to Capture Readiness, Acquisition Intelligence "
                  "and all future platform health reporting. Percentages permitted only for directly "
                  "measurable quantities; no opaque aggregation without explicit Executive approval. "
                  "Supersedable only by an ADR that explicitly does so."),
   "resolution_artifact": "docs/specs/WET-SPEC-REPORT-001_v1.0_Platform_Reporting_Standard.md",
   "resolution_date": "2026-08-22",
   "resolution_authority": "Executive Producer"},
}

entries = []
for r in ROWS:
    e = dict(zip(REQ, r))
    e.update(RESOLUTIONS.get(e["dwr_id"], {}))
    missing = [k for k in REQ if not e.get(k)]
    if missing:
        sys.exit(f"{r[0]} missing {missing}")
    entries.append(e)

doc = {
 "register_id": "DEFERRED_WORK_REGISTER",
 "conforms_to": "DWR-001 Deferred Work Register Standard v1.0",
 "version": "1.0.0",
 "status": "FOR EXECUTIVE REVIEW — recommendations only, no implementation authorized",
 "produced_by": "CAR-003 Platform Hygiene Review (PHI-001)",
 "date": "2026-08-22",
 "identifier_note": (
   "Entry identifiers DWR-NNN collide with the standard's own document ID (DWR-001). "
   "This review recommends renaming the standard to WET-SPEC-DWR-001, matching the "
   "named-series convention already used by WET-SPEC-DIE-001 and WET-SPEC-GATE-001, "
   "which frees the DWR-NNN space for entries. Flagged rather than silently resolved."),
 "class_definitions": {
   "DECISION": ("A question still requiring an Executive or Chairman ruling. Cannot be "
                "scheduled as engineering work until answered."),
   "IMPLEMENTATION": ("A decision already made and intentionally postponed. Can be "
                      "scheduled; needs capacity, not authority.")},
 "counts": {
   "total": len(entries),
   "deferred_decisions": sum(1 for e in entries if e["class"] == D),
   "deferred_implementations": sum(1 for e in entries if e["class"] == I)},
 "entries": entries,
}
with open("DEFERRED_WORK_REGISTER.yaml", "w") as f:
    f.write("# Deferred Work Register — produced by CAR-003 Platform Hygiene Review (PHI-001)\n")
    f.write("# FOR EXECUTIVE REVIEW. Recommendations only. No implementation authorized.\n")
    yaml.safe_dump(doc, f, sort_keys=False, width=100, allow_unicode=True)
print("entries:", len(entries), "| decisions:", doc["counts"]["deferred_decisions"],
      "| implementations:", doc["counts"]["deferred_implementations"])
