#!/usr/bin/env python3
"""Generate a Reference Execution scorecard from its governed sources.

The scorecard is a DERIVED artifact: it is regenerated, never hand-edited (DOC-002).
Inputs  : PRODUCTION_INTELLIGENCE_SEED.yaml (factual execution metrics)
          RE-NNN_META.yaml                  (facts the seed does not carry)
Outputs : RE-NNN_SCORECARD.yaml             (machine-readable fingerprint)
          RE_SCORECARD_INDEX.md             (regenerated across every scorecard found)

A scorecard carries no subjective score. Every field is a count, a ratio, a boolean or
a status read from a governed source.
"""
import sys, os, glob, datetime, yaml


def build(seed_path, meta_path):
    seed = yaml.safe_load(open(seed_path))
    meta = yaml.safe_load(open(meta_path))
    m = seed["metrics"]
    a = seed["automation_summary"]
    t0 = datetime.datetime.fromisoformat(meta["executed_start_utc"].replace("Z", "+00:00"))
    t1 = datetime.datetime.fromisoformat(meta["executed_end_utc"].replace("Z", "+00:00"))
    mins = round((t1 - t0).total_seconds() / 60.0, 1)

    return {
        "scorecard_class": "REFERENCE_EXECUTION_SCORECARD",
        "schema_version": "1.0",
        "re_id": meta["re_id"],
        "run_id": meta["run_id"],
        "title": meta["title"],
        "production": meta["production"],
        "sprint": meta["sprint"],
        "generated_from": {
            "seed": os.path.basename(seed_path),
            "meta": os.path.basename(meta_path),
        },
        "generated_note": "DERIVED — regenerate, never patch (DOC-002)",
        "fingerprint": {
            "execution_time_min": mins,
            "runtime_processed_s": m["runtime_processed_s"],
            "artifacts_hashed": meta["artifacts_hashed"],
            "input_hashes": meta["input_hashes"],
            "registries_updated": meta["registries_updated"],
            "timing_closure": seed["timing_closure_status"],
            "validation": seed["validation_status"],
            "executive_verdict": meta["executive_verdict"],
            "deltas_logged": m["deltas_logged"],
            "uncategorized_deltas": m["deltas_uncategorized"],
            "conflicts": m["conflicts_recorded"],
            "human_escalations": m["items_escalated_to_human"],
            "open_pdrs": len(meta["open_pdrs"]),
            "sync_coverage_pct": round(m["synchronization_coverage_fraction"] * 100, 1),
            "cue_coverage_pct": round(m["cue_coverage_fraction"] * 100, 1),
            "visual_events": m["visual_events_extracted"],
            "sync_rows": m["synchronization_rows"],
            "cues": m["cue_count"],
            "probes": f"{m['probes_passed']}/{m['probes_run']}",
            "music_generated": bool(a["music_generated"]),
            "biometric_operations": a["biometric_operations"],
            "sentiment_inferences": a["sentiment_inferences"],
            "frozen_documents_modified": meta["frozen_documents_modified"],
            "governance_violations": meta["governance_violations_detected"],
            "reference_status": meta["reference_status"],
        },
        "governance_violations_basis": meta["governance_violations_basis"],
        "context": meta["context"],
        "open_pdr_ids": meta["open_pdrs"],
        "gates_closed_against_this_re": meta["gates_closed_against_this_re"],
        "commits_produced": meta["commits_produced"],
    }


ROWS = [
    ("Execution time", "execution_time_min", "{} m"),
    ("Runtime processed", "runtime_processed_s", "{} s"),
    ("Artifacts hashed", "artifacts_hashed", "{}"),
    ("Input hashes", "input_hashes", "{}"),
    ("Timing closure", "timing_closure", "{}"),
    ("Validation", "validation", "{}"),
    ("Executive verdict", "executive_verdict", "{}"),
    ("Deltas logged", "deltas_logged", "{}"),
    ("Uncategorized deltas", "uncategorized_deltas", "{}"),
    ("Conflicts", "conflicts", "{}"),
    ("Human escalations", "human_escalations", "{}"),
    ("Open PDRs", "open_pdrs", "{}"),
    ("Sync coverage", "sync_coverage_pct", "{} %"),
    ("Cue coverage", "cue_coverage_pct", "{} %"),
    ("Visual events", "visual_events", "{}"),
    ("Probes passed", "probes", "{}"),
    ("Music generated", "music_generated", "{}"),
    ("Biometric operations", "biometric_operations", "{}"),
    ("Sentiment inferences", "sentiment_inferences", "{}"),
    ("Governance violations", "governance_violations", "{}"),
    ("Reference status", "reference_status", "{}"),
]


def index(dirpath):
    cards = []
    for p in sorted(glob.glob(os.path.join(dirpath, "RE-*_SCORECARD.yaml"))):
        cards.append(yaml.safe_load(open(p)))
    if not cards:
        return "No Reference Execution scorecards found.\n"

    L = ["# Reference Execution Scorecards — comparison index",
         "",
         "> DERIVED artifact. Regenerated by `scripts/re_scorecard.py`; never hand-edited (DOC-002).",
         "",
         "Every field is a count, a ratio, a boolean or a status read from a governed source. "
         "There is no subjective score, and none should be added — the value of a fingerprint is "
         "that it cannot be argued with.",
         ""]
    ids = [c["re_id"] for c in cards]
    L.append("| metric | " + " | ".join(ids) + " |")
    L.append("|---" * (len(ids) + 1) + "|")
    for label, key, fmt in ROWS:
        vals = [fmt.format(c["fingerprint"][key]) for c in cards]
        L.append(f"| {label} | " + " | ".join(vals) + " |")
    L.append("")
    L.append("## Comparability")
    L.append("")
    L.append("| context | " + " | ".join(ids) + " |")
    L.append("|---" * (len(ids) + 1) + "|")
    for k in ("visual_ground_truth_resolution", "survey_sheets_read_in_full",
              "survey_sheets_built", "correlation_segments_measurable",
              "correlation_segments_indeterminate"):
        vals = [str(c["context"].get(k, "—")) for c in cards]
        L.append(f"| {k.replace('_', ' ')} | " + " | ".join(vals) + " |")
    L.append("")
    L.append("**Read the context table before comparing the fingerprint table.** Visual-event counts, "
             "confidence distribution and DIE-V coverage are bounded by proxy resolution and sampling "
             "fraction. Two Reference Executions are comparable on those fields only when their context "
             "rows match.")
    L.append("")
    if len(cards) == 1:
        L.append("> **One row.** A scorecard index with a single entry records a baseline; it does not "
                 "yet show a trend. Continuous improvement becomes visible at RE-002, not before.")
        L.append("")
    return "\n".join(L)


if __name__ == "__main__":
    seed, meta, outdir = sys.argv[1], sys.argv[2], sys.argv[3]
    card = build(seed, meta)
    out = os.path.join(outdir, f"{card['re_id']}_SCORECARD.yaml")
    with open(out, "w") as f:
        f.write("# DERIVED — generated by scripts/re_scorecard.py. Regenerate, never patch (DOC-002).\n")
        yaml.safe_dump(card, f, sort_keys=False, default_flow_style=False, width=100)
    print("wrote", out)
    idx = os.path.join(outdir, "RE_SCORECARD_INDEX.md")
    open(idx, "w").write(index(outdir))
    print("wrote", idx)
